# Source inventory for conditional aria2 CMake targets.

set(ARIA2_SOURCES_BASE
  src/rpc/AddUriMethod.cc
  src/rpc/Ed2kMethods.cc
  src/rpc/Ed2kStatus.cc
  src/rpc/FileStatus.cc
  src/rpc/OptionMethods.cc
  src/rpc/RpcRequestHelpers.cc
  src/rpc/SessionMethods.cc
  src/rpc/SystemMethods.cc
  src/rpc/TaskControlMethods.cc
  src/rpc/TaskStatusMethods.cc
  src/rpc/TransferStatus.cc
  src/rpc/UriMethods.cc
  src/RequestGroupActions.cc
  src/ed2k/Ed2kPeerHandshake.cc
  src/ed2k/Ed2kServerHandshake.cc
  src/ed2k/Ed2kServerRequests.cc
  src/ed2k/Ed2kPeerRequests.cc
  src/ed2k/Ed2kCommandTransfer.cc
  src/ed2k/Ed2kConnectionIo.cc
  src/ed2k/Ed2kServerPackets.cc
  src/ed2k/Ed2kCommandSupport.cc
  src/ed2k/EmulePackets.cc
  src/ed2k/Ed2kPeerPackets.cc
  src/options/OptionCatalog.cc
  src/options/GeneralOptions.cc
  src/options/RpcOptions.cc
  src/options/StreamOptions.cc
  src/options/HttpOptions.cc
  src/options/SftpOptions.cc
  src/options/ProxyOptions.cc
  src/options/SharingOptions.cc
  src/options/BitTorrentOptions.cc
  src/options/MetalinkOptions.cc
  src/options/HelpOptions.cc
  src/stream/StreamStorage.cc
  src/stream/StreamScheduling.cc
  src/stream/StreamRequest.cc
  src/stream/StreamCompletion.cc
  src/stream/CurlHandle.cc
  src/transport/CurlMulti.cc
  src/transport/CurlOptions.cc
  src/transport/HttpHeaders.cc
  src/media/MediaDownload.cc
  src/media/MediaSession.cc
  src/media/DashFileIo.cc
  src/media/MediaJob.cc
  src/media/MediaInput.cc
  src/media/MediaCollection.cc
  src/media/MediaSegments.cc
  src/media/MediaPublication.cc
  src/media/MediaSelection.cc
  src/media/MediaEvents.cc
  src/media/MediaTransfer.cc
  src/media/MediaTransport.cc
  src/media/MediaRequest.cc
  src/media/MediaRequestContext.cc
  src/media/MuxInput.cc
  src/media/MuxPackets.cc
  src/media/MuxTimestamps.cc
  src/media/MuxOutput.cc
  src/media/MuxTimeline.cc
  src/media/MediaMuxer.cc
  src/media/MediaStore.cc
  src/a2algo.h
  src/a2functional.h
  src/a2io.h
  src/a2iterator.h
  src/a2netcompat.h
  src/a2time.h
  src/AbstractCommand.cc
  src/AbstractCommand.h
  src/AbstractDiskWriter.cc
  src/AbstractDiskWriter.h
  src/AbstractHttpServerResponseCommand.cc
  src/AbstractHttpServerResponseCommand.h
  src/AbstractOptionHandler.cc
  src/AbstractOptionHandler.h
  src/AbstractSingleDiskAdaptor.cc
  src/AbstractSingleDiskAdaptor.h
  src/AdaptiveFileAllocationIterator.cc
  src/AdaptiveFileAllocationIterator.h
  src/ApplicationStatePath.cc
  src/ApplicationStatePath.h
  src/AnonDiskWriterFactory.h
  src/array_fun.h
  src/StateSaveCommand.cc
  src/StateSaveCommand.h
  src/SystemResolver.cc
  src/SystemResolver.h
  src/base32.cc
  src/base32.h
  src/base64.h
  src/BinaryStream.h
  src/bitfield.h
  src/BitfieldMan.cc
  src/BitfieldMan.h
  src/BufferedFile.cc
  src/BufferedFile.h
  src/ByteArrayDiskWriter.cc
  src/ByteArrayDiskWriter.h
  src/ByteArrayDiskWriterFactory.h
  src/CheckIntegrityCommand.cc
  src/CheckIntegrityCommand.h
  src/CheckIntegrityDispatcherCommand.cc
  src/CheckIntegrityDispatcherCommand.h
  src/CheckIntegrityEntry.cc
  src/CheckIntegrityEntry.h
  src/CheckIntegrityMan.h
  src/Checksum.cc
  src/Checksum.h
  src/ChecksumCheckIntegrityEntry.cc
  src/ChecksumCheckIntegrityEntry.h
  src/ChunkChecksum.cc
  src/ChunkChecksum.h
  src/ChunkedDecodingStreamFilter.cc
  src/ChunkedDecodingStreamFilter.h
  src/ColorizedStream.cc
  src/ColorizedStream.h
  src/Command.cc
  src/Command.h
  src/common.h
  src/console.cc
  src/console.h
  src/ConsoleStatCalc.cc
  src/ConsoleStatCalc.h
  src/ContentTypeRequestGroupCriteria.cc
  src/ContentTypeRequestGroupCriteria.h
  src/Context.cc
  src/Context.h
  src/ContextAttribute.cc
  src/ContextAttribute.h
  src/CUIDCounter.cc
  src/CUIDCounter.h
  src/CurlDownload.cc
  src/CurlDownload.h
  src/CurlDownloadCommand.cc
  src/CurlDownloadCommand.h
  src/CurlDownloadImpl.h
  src/CurlSession.cc
  src/CurlSession.h
  src/CurlCheckIntegrityEntry.cc
  src/CurlCheckIntegrityEntry.h
  src/DefaultDiskWriter.cc
  src/DefaultDiskWriter.h
  src/DefaultDiskWriterFactory.cc
  src/DefaultDiskWriterFactory.h
  src/DefaultPieceStorage.cc
  src/DefaultPieceStorage.h
  src/DefaultStreamPieceSelector.cc
  src/DefaultStreamPieceSelector.h
  src/DelayedCommand.h
  src/Dependency.h
  src/DirectDiskAdaptor.cc
  src/DirectDiskAdaptor.h
  src/DiskAdaptor.cc
  src/DiskAdaptor.h
  src/DiskWriter.h
  src/DiskWriterFactory.h
  src/DlAbortEx.cc
  src/DlAbortEx.h
  src/DlRetryEx.cc
  src/DlRetryEx.h
  src/DNSCache.cc
  src/DNSCache.h
  src/DownloadContext.cc
  src/DownloadContext.h
  src/DownloadEngine.cc
  src/DownloadEngine.h
  src/DownloadEngineFactory.cc
  src/DownloadEngineFactory.h
  src/DownloadFailureException.cc
  src/DownloadFailureException.h
  src/DownloadHandler.cc
  src/DownloadHandler.h
  src/DownloadHandlerConstants.cc
  src/DownloadHandlerConstants.h
  src/DownloadResult.cc
  src/DownloadResult.h
  src/download_handlers.cc
  src/download_handlers.h
  src/download_helper.cc
  src/download_helper.h
  src/Ed2kAttribute.cc
  src/ed2k/Ed2kSources.cc
  src/ed2k/Ed2kPeerState.cc
  src/ed2k/Ed2kSearchState.cc
  src/ed2k/Ed2kIntegrityState.cc
  src/ed2k/Ed2kCallbackState.cc
  src/ed2k/Ed2kRequestedRanges.cc
  src/ed2k/Ed2kKadStateIntegration.cc
  src/ed2k/Ed2kServerState.cc
  src/ed2k/Ed2kScheduling.cc
  src/Ed2kAttribute.h
  src/Ed2kCommand.cc
  src/Ed2kCommand.h
  src/Ed2kListenCommand.cc
  src/Ed2kListenCommand.h
  src/Ed2kPeerTransfer.cc
  src/Ed2kPeerTransfer.h
  src/Ed2kSession.cc
  src/Ed2kSession.h
  src/Ed2kSharingTimeSeedCriteria.cc
  src/Ed2kSharingTimeSeedCriteria.h
  src/Ed2kStore.cc
  src/Ed2kStore.h
  src/Ed2kShareIndex.cc
  src/Ed2kShareIndex.h
  src/Ed2kSharedFile.cc
  src/Ed2kSharedFile.h
  src/Ed2kSharedResponder.cc
  src/Ed2kSharedResponder.h
  src/Ed2kUploadQueue.cc
  src/Ed2kUploadQueue.h
  src/Ed2kKadCommand.cc
  src/ed2k/KadRoutingPackets.cc
  src/ed2k/KadSearchPackets.cc
  src/ed2k/KadFirewallPackets.cc
  src/ed2k/KadPeerPackets.cc
  src/ed2k/KadServerPackets.cc
  src/ed2k/KadDatagrams.cc
  src/ed2k/KadObfuscation.cc
  src/ed2k/KadServerRequests.cc
  src/ed2k/KadMaintenance.cc
  src/ed2k/KadTraversal.cc
  src/ed2k/KadPeerRequests.cc
  src/ed2k/KadCommandSupport.cc
  src/Ed2kKadCommand.h
  src/Ed2kKadState.cc
  src/Ed2kKadState.h
  src/DHKeyExchange.h
  src/MSEDHKeyExchange.h
  src/ed2k_aich.cc
  src/ed2k_aich.h
  src/ed2k_compression.cc
  src/ed2k_compression.h
  src/ed2k_constants.h
  src/ed2k_crypto.cc
  src/ed2k_crypto.h
  src/ed2k_endpoint.cc
  src/ed2k_endpoint.h
  src/ed2k_hash.cc
  src/ed2k_hash.h
  src/ed2k_kad.cc
  src/ed2k_kad.h
  src/ed2k_link.cc
  src/ed2k_link.h
  src/ed2k_kad_search.cc
  src/ed2k_kad_search.h
  src/ed2k_packet.cc
  src/ed2k_packet.h
  src/ed2k_peer.cc
  src/ed2k_peer.h
  src/ed2k_policy.cc
  src/ed2k_policy.h
  src/ed2k_search.cc
  src/ed2k_search.h
  src/ed2k_server.cc
  src/ed2k_server.h
  src/error_code.h
  src/Event.h
  src/EventPoll.h
  src/Exception.cc
  src/Exception.h
  src/FatalException.cc
  src/FatalException.h
  src/FeatureConfig.cc
  src/FeatureConfig.h
  src/File.cc
  src/File.h
  src/FileAllocationCommand.cc
  src/FileAllocationCommand.h
  src/FileAllocationDispatcherCommand.cc
  src/FileAllocationDispatcherCommand.h
  src/FileAllocationEntry.cc
  src/FileAllocationEntry.h
  src/FileAllocationIterator.h
  src/FileAllocationMan.h
  src/FileEntry.cc
  src/FileEntry.h
  src/FillRequestGroupCommand.cc
  src/FillRequestGroupCommand.h
  src/fmt.cc
  src/fmt.h
  src/GenericParser.h
  src/GeomStreamPieceSelector.cc
  src/GeomStreamPieceSelector.h
  src/GroupId.cc
  src/GroupId.h
  src/GrowSegment.cc
  src/GrowSegment.h
  src/HaveEraseCommand.cc
  src/HaveEraseCommand.h
  src/help_tags.cc
  src/help_tags.h
  src/HttpHeader.cc
  src/HttpHeader.h
  src/HttpHeaderProcessor.cc
  src/HttpHeaderProcessor.h
  src/HttpListenCommand.cc
  src/HttpListenCommand.h
  src/HttpServer.cc
  src/HttpServer.h
  src/HttpServerBodyCommand.cc
  src/HttpServerBodyCommand.h
  src/HttpServerCommand.cc
  src/HttpServerCommand.h
  src/HttpServerResponseCommand.cc
  src/HttpServerResponseCommand.h
  src/IndexedList.h
  src/InorderStreamPieceSelector.cc
  src/InorderStreamPieceSelector.h
  src/RandomStreamPieceSelector.cc
  src/RandomStreamPieceSelector.h
  src/InorderURISelector.cc
  src/InorderURISelector.h
  src/IOFile.cc
  src/IOFile.h
  src/IteratableChecksumValidator.cc
  src/IteratableChecksumValidator.h
  src/IteratableChunkChecksumValidator.cc
  src/IteratableChunkChecksumValidator.h
  src/IteratableValidator.h
  src/json.cc
  src/json.h
  src/JsonDiskWriter.h
  src/JsonParser.cc
  src/JsonParser.h
  src/LegacyInputAdapter.cc
  src/LegacyInputAdapter.h
  src/Log.cc
  src/Log.h
  src/MemoryBufferPreDownloadHandler.h
  src/MemoryPreDownloadHandler.h
  src/message.h
  src/MessageDigest.cc
  src/MessageDigest.h
  src/MessageDigestImpl.h
  src/message_digest_helper.cc
  src/message_digest_helper.h
  src/MetadataInfo.cc
  src/MetadataInfo.h
  src/MetalinkHttpEntry.cc
  src/MetalinkHttpEntry.h
  src/MultiDiskAdaptor.cc
  src/MultiDiskAdaptor.h
  src/MultiFileAllocationIterator.cc
  src/MultiFileAllocationIterator.h
  src/MultiUrlRequestInfo.cc
  src/MultiUrlRequestInfo.h
  src/NetStat.cc
  src/NetStat.h
  src/Notifier.cc
  src/Notifier.h
  src/NullOutputFile.h
  src/NullSinkStreamFilter.cc
  src/NullSinkStreamFilter.h
  src/NullStatCalc.h
  src/Option.cc
  src/Option.h
  src/OptionHandler.cc
  src/OptionHandler.h
  src/OptionHandlerException.cc
  src/OptionHandlerException.h
  src/OptionHandlerImpl.cc
  src/OptionHandlerImpl.h
  src/OptionParser.cc
  src/OptionParser.h
  src/option_processing.cc
  src/OutputFile.h
  src/paramed_string.cc
  src/paramed_string.h
  src/PeerStat.cc
  src/PeerStat.h
  src/Piece.cc
  src/Piece.h
  src/PiecedSegment.cc
  src/PiecedSegment.h
  src/PieceHashCheckIntegrityEntry.cc
  src/PieceHashCheckIntegrityEntry.h
  src/PieceSelector.h
  src/PieceStatMan.cc
  src/PieceStatMan.h
  src/PieceStorage.h
  src/Platform.cc
  src/Platform.h
  src/PostDownloadHandler.h
  src/PreDownloadHandler.h
  src/prefs.cc
  src/prefs.h
  src/ProgressAwareEntry.h
  src/ProtocolDetector.cc
  src/ProtocolDetector.h
  src/Randomizer.h
  src/Range.cc
  src/Range.h
  src/RarestPieceSelector.cc
  src/RarestPieceSelector.h
  src/RealtimeCommand.cc
  src/RealtimeCommand.h
  src/RecoverableException.cc
  src/RecoverableException.h
  src/Request.cc
  src/Request.h
  src/RequestGroup.cc
  src/task/Ed2kTask.cc
  src/task/TaskStorage.cc
  src/task/TaskProgress.cc
  src/task/TaskResults.cc
  src/task/TaskHandlers.cc
  src/RequestGroup.h
  src/RangePlanner.cc
  src/RangePlanner.h
  src/RequestGroupCriteria.h
  src/RequestGroupEntry.cc
  src/RequestGroupEntry.h
  src/RequestGroupMan.cc
  src/task/TaskManagerQueue.cc
  src/task/TaskEvents.cc
  src/task/TaskManagerStop.cc
  src/task/TaskManagerStorage.cc
  src/task/TaskManagerResults.cc
  src/task/TaskManagerOutput.cc
  src/task/TaskManagerStats.cc
  src/RequestGroupMan.h
  src/RpcMethod.cc
  src/RpcMethod.h
  src/RpcMethodFactory.cc
  src/RpcMethodFactory.h
  src/RpcRequest.cc
  src/RpcRequest.h
  src/RpcResponse.cc
  src/RpcResponse.h
  src/rpc_helper.cc
  src/rpc_helper.h
  src/SaveSessionCommand.h
  src/SaveSessionCommand.cc
  src/SeedCheckCommand.cc
  src/SeedCheckCommand.h
  src/SeedCriteria.h
  src/SegList.h
  src/Segment.h
  src/SegmentMan.cc
  src/SegmentMan.h
  src/SelectEventPoll.cc
  src/SelectEventPoll.h
  src/SequentialDispatcherCommand.h
  src/SequentialPicker.h
  src/ServerStat.cc
  src/ServerStat.h
  src/ServerStatMan.cc
  src/ServerStatMan.h
  src/SessionSerializer.cc
  src/SessionSerializer.h
  src/ShareRatioSeedCriteria.cc
  src/ShareRatioSeedCriteria.h
  src/Signature.cc
  src/Signature.h
  src/SimpleRandomizer.cc
  src/SimpleRandomizer.h
  src/SingleFileAllocationIterator.cc
  src/SingleFileAllocationIterator.h
  src/SingletonHolder.h
  src/SinkStreamFilter.cc
  src/SinkStreamFilter.h
  src/SocketBuffer.cc
  src/SocketBuffer.h
  src/SocketCore.cc
  src/platform/SocketOps.cc
  src/platform/SocketTls.cc
  src/platform/SocketInterfaces.cc
  src/platform/SocketOptions.cc
  src/platform/SocketIo.cc
  src/platform/SocketAddress.cc
  src/SocketCore.h
  src/SocketRecvBuffer.cc
  src/SocketRecvBuffer.h
  src/SpeedCalc.cc
  src/SpeedCalc.h
  src/StatCalc.h
  src/StreamFilter.cc
  src/StreamFilter.h
  src/StreamPieceSelector.h
  src/StreamStore.cc
  src/StreamStore.h
  src/StructParserStateMachine.h
  src/TimeA2.cc
  src/TimeA2.h
  src/TimeBasedCommand.cc
  src/TimeBasedCommand.h
  src/TimedHaltCommand.cc
  src/TimedHaltCommand.h
  src/TimerA2.cc
  src/TimerA2.h
  src/timespec.h
  src/TransferStat.h
  src/UnionSeedCriteria.cc
  src/UnionSeedCriteria.h
  src/TruncFileAllocationIterator.cc
  src/TruncFileAllocationIterator.h
  src/UnknownLengthPieceStorage.cc
  src/UnknownLengthPieceStorage.h
  src/UnknownOptionException.cc
  src/UnknownOptionException.h
  src/uri.cc
  src/uri.h
  src/UriListParser.cc
  src/UriListParser.h
  src/URIResult.cc
  src/URIResult.h
  src/URISelector.h
  src/uri_split.c
  src/uri_split.h
  src/usage_text.h
  src/platform/NativeText.cc
  src/support/Text.cc
  src/support/Numbers.cc
  src/support/Encoding.cc
  src/support/FilePath.cc
  src/support/Network.cc
  src/support/Storage.cc
  src/support/Random.cc
  src/platform/Process.cc
  src/support/ContentDisposition.cc
  src/support/OutputName.cc
  src/util_security.cc
  src/util_security.h
  src/ValueBase.cc
  src/ValueBase.h
  src/ValueBaseDiskWriter.h
  src/ValueBaseJsonParser.h
  src/ValueBaseStructParserState.h
  src/ValueBaseStructParserStateImpl.cc
  src/ValueBaseStructParserStateImpl.h
  src/ValueBaseStructParserStateMachine.cc
  src/ValueBaseStructParserStateMachine.h
  src/version_usage.cc
  src/wallclock.cc
  src/wallclock.h
  src/WatchProcessCommand.cc
  src/WatchProcessCommand.h
  src/WrDiskCache.cc
  src/WrDiskCache.h
  src/WrDiskCacheEntry.cc
  src/WrDiskCacheEntry.h
  src/XmlRpcRequestParserController.cc
  src/XmlRpcRequestParserController.h
  src/OpenedFileCounter.cc
  src/OpenedFileCounter.h
  src/SHA1IOFile.cc
  src/SHA1IOFile.h
)

set(ARIA2_SOURCES_MINGW_BUILD
  src/WinConsoleFile.cc
  src/WinConsoleFile.h
)

set(ARIA2_SOURCES_ENABLE_WEBSOCKET
  src/WebSocketInteractionCommand.cc
  src/WebSocketInteractionCommand.h
  src/WebSocketResponseCommand.cc
  src/WebSocketResponseCommand.h
  src/WebSocketSession.cc
  src/WebSocketSession.h
  src/WebSocketSessionMan.cc
  src/WebSocketSessionMan.h
)

set(ARIA2_SOURCES_NOT_ENABLE_WEBSOCKET
  src/NullWebSocketSessionMan.h
)

set(ARIA2_SOURCES_XML
  src/ParserStateMachine.h
  src/XmlAttr.cc
  src/XmlAttr.h
  src/XmlParser.cc
  src/XmlParser.h
)

set(ARIA2_SOURCES_HAVE_LIBEXPAT
  src/ExpatXmlParser.cc
  src/ExpatXmlParser.h
)

set(ARIA2_SOURCES_ENABLE_XML_RPC
  src/XmlRpcDiskWriter.cc
  src/XmlRpcDiskWriter.h
  src/XmlRpcRequestParserState.h
  src/XmlRpcRequestParserStateImpl.cc
  src/XmlRpcRequestParserStateImpl.h
  src/XmlRpcRequestParserStateMachine.cc
  src/XmlRpcRequestParserStateMachine.h
)

set(ARIA2_SOURCES_HAVE_SOME_FALLOCATE
  src/FallocFileAllocationIterator.cc
  src/FallocFileAllocationIterator.h
)

set(ARIA2_SOURCES_HAVE_EPOLL
  src/EpollEventPoll.cc
  src/EpollEventPoll.h
)

set(ARIA2_SOURCES_ENABLE_SSL
  src/TLSContext.h
  src/TLSSession.h
)

set(ARIA2_SOURCES_OPENSSL_CRYPTO
  src/LibsslDHKeyExchange.cc
  src/LibsslDHKeyExchange.h
  src/LibsslMessageDigestImpl.cc
)

set(ARIA2_SOURCES_HAVE_OPENSSL_TLS
  src/LibsslTLSContext.cc
  src/LibsslTLSContext.h
  src/LibsslTLSSession.cc
  src/LibsslTLSSession.h
)

set(ARIA2_SOURCES_APPLE_STATE_PATH
  src/ApplicationStatePathApple.mm
)

set(ARIA2_SOURCES_WINDOWS_STATE_PATH
  src/ApplicationStatePathWindows.cc
)

set(ARIA2_SOURCES_POSIX_STATE_PATH
  src/ApplicationStatePathPosix.cc
)

set(ARIA2_SOURCES_HAVE_ZLIB
  src/GZipDecodingStreamFilter.cc
  src/GZipDecodingStreamFilter.h
  src/GZipEncoder.cc
  src/GZipEncoder.h
  src/GZipFile.cc
  src/GZipFile.h
  src/Adler32MessageDigestImpl.cc
  src/Adler32MessageDigestImpl.h
)

set(ARIA2_SOURCES_HAVE_SQLITE3
)

set(ARIA2_SOURCES_ENABLE_BITTORRENT
  src/rpc/TorrentControlMethods.cc
  src/rpc/TorrentMetadataMethods.cc
  src/rpc/TorrentStatus.cc
  src/rpc/TorrentStatusMethods.cc
  src/bittorrent/BtStateIntegration.cc
  src/bittorrent/BtStatusProjection.cc
  src/bittorrent/BtSelection.cc
  src/bittorrent/BtTaskLifecycle.cc
  src/bittorrent/BtSessionControl.cc
  src/bittorrent/BtTaskAlerts.cc
  src/bittorrent/BtResumeAlerts.cc
  src/bittorrent/BtProgressAlerts.cc
  src/bittorrent/BtNetworkAlerts.cc
  src/BtDownload.cc
  src/bittorrent/BtDownloadSupport.cc
  src/bittorrent/BtMetainfo.cc
  src/bittorrent/BtResume.cc
  src/bittorrent/BtTrackers.cc
  src/bittorrent/BtConfiguration.cc
  src/bittorrent/BtFileSelection.cc
  src/bittorrent/BtProgress.cc
  src/BtDownload.h
  src/BtDownloadImpl.h
  src/BtDownloadCommand.cc
  src/BtDownloadCommand.h
  src/BtMetadata.cc
  src/BtMetadata.h
  src/BtPeerBlocklist.cc
  src/BtPeerBlocklist.h
  src/BtPostDownloadHandler.cc
  src/BtPostDownloadHandler.h
  src/BtStateStore.cc
  src/BtStateStore.h
  src/BtSession.cc
  src/BtSession.h
  src/BtSettings.cc
  src/BtSettings.h
  src/BtSnapshot.cc
  src/BtSnapshot.h
)

set(ARIA2_SOURCES_ARC4
  src/ARC4Encryptor.cc
  src/ARC4Encryptor.h
)

set(ARIA2_SOURCES_ENABLE_METALINK
  src/rpc/MetalinkMethods.cc
  src/Metalink2RequestGroup.cc
  src/Metalink2RequestGroup.h
  src/MetalinkEntry.cc
  src/MetalinkEntry.h
  src/Metalinker.cc
  src/Metalinker.h
  src/MetalinkMetaurl.cc
  src/MetalinkMetaurl.h
  src/MetalinkParserController.cc
  src/MetalinkParserController.h
  src/MetalinkParserState.h
  src/MetalinkParserStateImpl.cc
  src/MetalinkParserStateImpl.h
  src/MetalinkParserStateMachine.cc
  src/MetalinkParserStateMachine.h
  src/MetalinkParserStateV3Impl.cc
  src/MetalinkParserStateV3Impl.h
  src/MetalinkParserStateV4Impl.cc
  src/MetalinkParserStateV4Impl.h
  src/MetalinkPostDownloadHandler.cc
  src/MetalinkPostDownloadHandler.h
  src/MetalinkResource.cc
  src/MetalinkResource.h
  src/metalink_helper.cc
  src/metalink_helper.h
)

set(ARIA2_SOURCES_NOT_HAVE_GAI_STRERROR
  src/gai_strerror.c
  src/gai_strerror.h
)

set(ARIA2_SOURCES_NOT_HAVE_GETTIMEOFDAY
  src/gettimeofday.c
  src/gettimeofday.h
)

set(ARIA2_SOURCES_NOT_HAVE_LOCALTIME_R
  src/localtime_r.c
  src/localtime_r.h
)

set(ARIA2_SOURCES_NOT_HAVE_STRPTIME
  src/strptime.c
  src/strptime.h
)

set(ARIA2_SOURCES_NOT_HAVE_TIMEGM
  src/timegm.c
  src/timegm.h
)

set(ARIA2_SOURCES_NOT_HAVE_DAEMON
  src/daemon.cc
  src/daemon.h
)

set(ARIA2_SOURCES_HAVE_POLL
  src/PollEventPoll.cc
  src/PollEventPoll.h
)

set(ARIA2_SOURCES_HAVE_KQUEUE
  src/KqueueEventPoll.cc
  src/KqueueEventPoll.h
)

set(ARIA2_SOURCES_ENABLE_LIBARIA2
  src/ApiCallbackDownloadEventListener.cc
  src/ApiCallbackDownloadEventListener.h
  src/aria2api.cc
  src/aria2api.h
  src/KeepRunningCommand.cc
  src/KeepRunningCommand.h
)
