# Source inventory for conditional aria2 CTest targets.

set(ARIA2_TEST_SOURCES_BASE
  tests/AllTest.cc
  tests/a2doctest.h
  tests/TestUtil.cc
  tests/TestUtil.h
  tests/SocketCoreTest.cc
  tests/SocketTlsTest.cc
  tests/SystemResolverTest.cc
  tests/array_funTest.cc
  tests/Base64Test.cc
  tests/Base32Test.cc
  tests/a2functionalTest.cc
  tests/ApplicationStatePathTest.cc
  tests/StreamStoreTest.cc
  tests/MediaTest.cc
  tests/CurlSessionTest.cc
  tests/FileEntryTest.cc
  tests/PieceTest.cc
  tests/SegmentTest.cc
  tests/GrowSegmentTest.cc
  tests/SingleFileAllocationIteratorTest.cc
  tests/RequestGroupTest.cc
  tests/RangePlannerTest.cc
  tests/support/TextMatchTest.cc
  tests/support/TextSplitTest.cc
  tests/support/ContentDispositionTest.cc
  tests/support/ExtendedFilenameTest.cc
  tests/support/EncodingTest.cc
  tests/support/NumbersTest.cc
  tests/support/FilePathTest.cc
  tests/support/NetworkTest.cc
  tests/UtilSecurityTest.cc
  tests/UriListParserTest.cc
  tests/HttpHeaderProcessorTest.cc
  tests/RequestTest.cc
  tests/RequestGroupManTest.cc
  tests/LogTest.cc
  tests/ShareRatioSeedCriteriaTest.cc
  tests/OptionHandlerTest.cc
  tests/SegmentManTest.cc
  tests/BitfieldManTest.cc
  tests/HttpHeaderTest.cc
  tests/FileTest.cc
  tests/OptionTest.cc
  tests/DefaultDiskWriterTest.cc
  tests/FeatureConfigTest.cc
  tests/VersionUsageTest.cc
  tests/SpeedCalcTest.cc
  tests/MultiDiskAdaptorTest.cc
  tests/MultiFileAllocationIteratorTest.cc
  tests/ProtocolDetectorTest.cc
  tests/ExceptionTest.cc
  tests/DownloadHandlersTest.cc
  tests/SignatureTest.cc
  tests/ServerStatManTest.cc
  tests/InorderURISelectorTest.cc
  tests/ServerStatTest.cc
  tests/DirectDiskAdaptorTest.cc
  tests/TimeTest.cc
  tests/LegacyInputAdapterTest.cc
  tests/OptionParserTest.cc
  tests/DNSCacheTest.cc
  tests/DownloadHelperTest.cc
  tests/ed2k/TaskBootstrapTest.cc
  tests/ed2k/SourcePolicyTest.cc
  tests/ed2k/PeerConnectionPolicyTest.cc
  tests/ed2k/PeerReaskTest.cc
  tests/ed2k/DatagramSchedulingTest.cc
  tests/ed2k/ServerSchedulingTest.cc
  tests/ed2k/RequestedRangesTest.cc
  tests/SequentialPickerTest.cc
  tests/RarestPieceSelectorTest.cc
  tests/PieceStatManTest.cc
  tests/a2algoTest.cc
  tests/bitfieldTest.cc
  tests/DownloadContextTest.cc
  tests/SessionSerializerTest.cc
  tests/ValueBaseTest.cc
  tests/ChunkedDecodingStreamFilterTest.cc
  tests/UriTest.cc
  tests/UriSplitTest.cc
  tests/MockSegment.h
  tests/JsonTest.cc
  tests/ValueBaseJsonParserTest.cc
  tests/RpcResponseTest.cc
  tests/rpc/RpcTestSupport.cc
  tests/rpc/RpcTestSupport.h
  tests/rpc/SystemMethodsTest.cc
  tests/rpc/UriMethodsTest.cc
  tests/rpc/MetainfoMethodsTest.cc
  tests/rpc/MetalinkMethodsTest.cc
  tests/rpc/OptionMethodsTest.cc
  tests/rpc/Ed2kMethodsTest.cc
  tests/rpc/TransferStatusTest.cc
  tests/rpc/BitTorrentSessionTest.cc
  tests/rpc/BitTorrentSelectionTest.cc
  tests/rpc/TaskControlTest.cc
  tests/WebSocketSessionManTest.cc
  tests/BufferedFileTest.cc
  tests/GeomStreamPieceSelectorTest.cc
  tests/SegListTest.cc
  tests/ParamedStringTest.cc
  tests/RpcHelperTest.cc
  tests/SinkStreamFilterTest.cc
  tests/WrDiskCacheTest.cc
  tests/WrDiskCacheEntryTest.cc
  tests/GroupIdTest.cc
  tests/IndexedListTest.cc
  tests/MessageDigestHelperTest.cc
  tests/IteratableChunkChecksumValidatorTest.cc
  tests/IteratableChecksumValidatorTest.cc
  tests/MessageDigestTest.cc
  tests/ed2k/LinkTest.cc
  tests/ed2k/PeerCodecTest.cc
  tests/ed2k/ServerCodecTest.cc
  tests/ed2k/SearchCodecTest.cc
  tests/ed2k/CompressionTest.cc
  tests/ed2k/IntegrityCodecTest.cc
  tests/ed2k/KadPacketTest.cc
  tests/ed2k/StateCodecTest.cc
  tests/Ed2kPolicyWindowsMacroSmokeTest.cc
  tests/ed2k/CommandTestSupport.cc
  tests/ed2k/CommandTestSupport.h
  tests/ed2k/ServerCommandTest.cc
  tests/ed2k/PeerCommandTest.cc
  tests/ed2k/PeerObfuscationTest.cc
  tests/ed2k/TaskLifecycleTest.cc
  tests/ed2k/KadCommandTest.cc
  tests/Ed2kKadStateTest.cc
  tests/Ed2kSessionTest.cc
  tests/Ed2kStoreTest.cc
  tests/Ed2kShareIndexTest.cc
  tests/Ed2kUploadQueueTest.cc
)

set(ARIA2_TEST_SOURCES_ENABLE_XML_RPC
  tests/XmlRpcRequestParserControllerTest.cc
)

set(ARIA2_TEST_SOURCES_HAVE_SOME_FALLOCATE
  tests/FallocFileAllocationIteratorTest.cc
)

set(ARIA2_TEST_SOURCES_HAVE_ZLIB
  tests/GZipDecoder.cc
  tests/GZipDecoder.h
  tests/GZipDecoderTest.cc
  tests/GZipEncoderTest.cc
  tests/GZipDecodingStreamFilterTest.cc
  tests/GZipFileTest.cc
)

set(ARIA2_TEST_SOURCES_ENABLE_BITTORRENT
  tests/BtDownloadTest.cc
  tests/BtPeerBlocklistTest.cc
  tests/BtSessionTest.cc
)

set(ARIA2_TEST_SOURCES_ENABLE_METALINK
  tests/MetalinkerTest.cc
  tests/MetalinkEntryTest.cc
  tests/Metalink2RequestGroupTest.cc
  tests/MetalinkPostDownloadHandlerTest.cc
  tests/MetalinkHelperTest.cc
  tests/MetalinkParserControllerTest.cc
  tests/metalink/Version4Test.cc
  tests/metalink/Version3Test.cc
  tests/metalink/InputValidationTest.cc
  tests/metalink/PieceValidationTest.cc
)

set(ARIA2_TEST_SOURCES_NOT_HAVE_TIMEGM
  tests/TimegmTest.cc
)

set(ARIA2_TEST_SOURCES_ENABLE_LIBARIA2
  tests/Aria2ApiTest.cc
)
