enable-rpc=true
rpc-listen-all=true
rpc-listen-port=6800

dir=/downloads
input-file=/var/lib/aria2-next/session.txt
save-session=/var/lib/aria2-next/session.txt
save-session-interval=60
auto-save-interval=60
continue=true

max-concurrent-downloads=5
max-connection-per-server=8
split=8
