my %targets = (
    "mingw-arm64" => {
        inherit_from => [ "mingw-common" ],
        CC           => "clang",
        CXX          => "clang++",
        sys_id       => "MINGW64",
        bn_ops       => "SIXTY_FOUR_BIT",
        uplink_arch  => undef,
        multilib     => "64",
    },
);
