include(ExternalProject)
include(ProcessorCount)

find_program(ARIA2_MAKE_EXECUTABLE make REQUIRED)
find_package(Perl REQUIRED)
ProcessorCount(ARIA2_BUILD_JOBS)
if(NOT ARIA2_BUILD_JOBS)
  set(ARIA2_BUILD_JOBS 2)
endif()

set(ARIA2_VENDOR_ROOT "${CMAKE_SOURCE_DIR}/third_party")
set(ARIA2_DEPENDENCY_PREFIX "${CMAKE_BINARY_DIR}/dependencies")
set(ARIA2_INNER_BINARY_DIR "${CMAKE_BINARY_DIR}/source")

foreach(tool_variable
    CMAKE_C_COMPILER
    CMAKE_CXX_COMPILER
    CMAKE_RC_COMPILER
    CMAKE_AR
    CMAKE_RANLIB)
  if(DEFINED ${tool_variable} AND NOT "${${tool_variable}}" STREQUAL "")
    cmake_path(IS_ABSOLUTE ${tool_variable} tool_is_absolute)
    if(NOT tool_is_absolute)
      unset(resolved_tool CACHE)
      find_program(resolved_tool
        NAMES "${${tool_variable}}"
        NO_CMAKE_FIND_ROOT_PATH
        REQUIRED)
      set(${tool_variable} "${resolved_tool}")
    endif()
  endif()
endforeach()

set(ARIA2_EXTERNAL_CMAKE_ARGS
  -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
  -DCMAKE_INSTALL_PREFIX=${ARIA2_DEPENDENCY_PREFIX}
  -DCMAKE_POSITION_INDEPENDENT_CODE=ON)

foreach(variable
    CMAKE_TOOLCHAIN_FILE
    CMAKE_OSX_ARCHITECTURES
    CMAKE_OSX_DEPLOYMENT_TARGET
    CMAKE_C_COMPILER
    CMAKE_CXX_COMPILER
    CMAKE_C_COMPILER_TARGET
    CMAKE_CXX_COMPILER_TARGET
    CMAKE_SYSROOT
    CMAKE_C_FLAGS
    CMAKE_CXX_FLAGS
    CMAKE_OBJCXX_FLAGS
    CMAKE_EXE_LINKER_FLAGS
    CMAKE_RC_COMPILER
    CMAKE_AR
    CMAKE_RANLIB)
  if(DEFINED ${variable} AND NOT "${${variable}}" STREQUAL "")
    list(APPEND ARIA2_EXTERNAL_CMAKE_ARGS -D${variable}=${${variable}})
  endif()
endforeach()

if(CMAKE_CROSSCOMPILING)
  foreach(variable
    CMAKE_SYSTEM_NAME
    CMAKE_SYSTEM_PROCESSOR
    CMAKE_SYSTEM_VERSION
    CMAKE_ANDROID_NDK
    CMAKE_ANDROID_ARCH_ABI
    CMAKE_ANDROID_STL_TYPE)
    if(DEFINED ${variable} AND NOT "${${variable}}" STREQUAL "")
      list(APPEND ARIA2_EXTERNAL_CMAKE_ARGS -D${variable}=${${variable}})
    endif()
  endforeach()
endif()

ExternalProject_Add(zlib_project
  SOURCE_DIR "${ARIA2_VENDOR_ROOT}/zlib"
  BINARY_DIR "${CMAKE_BINARY_DIR}/vendor/zlib"
  CMAKE_ARGS
    ${ARIA2_EXTERNAL_CMAKE_ARGS}
    -DZLIB_BUILD_SHARED=OFF
    -DZLIB_BUILD_STATIC=ON
    -DZLIB_BUILD_TESTING=OFF
  UPDATE_COMMAND ""
  TEST_COMMAND "")

ExternalProject_Add(expat_project
  SOURCE_DIR "${ARIA2_VENDOR_ROOT}/expat"
  BINARY_DIR "${CMAKE_BINARY_DIR}/vendor/expat"
  CMAKE_ARGS
    ${ARIA2_EXTERNAL_CMAKE_ARGS}
    -DEXPAT_SHARED_LIBS=OFF
    -DEXPAT_BUILD_DOCS=OFF
    -DEXPAT_BUILD_EXAMPLES=OFF
    -DEXPAT_BUILD_TESTS=OFF
    -DEXPAT_BUILD_TOOLS=OFF
  UPDATE_COMMAND ""
  TEST_COMMAND "")

ExternalProject_Add(sqlite_project
  SOURCE_DIR "${ARIA2_VENDOR_ROOT}/sqlite"
  BINARY_DIR "${CMAKE_BINARY_DIR}/vendor/sqlite"
  CMAKE_ARGS ${ARIA2_EXTERNAL_CMAKE_ARGS}
  UPDATE_COMMAND ""
  TEST_COMMAND "")

if(APPLE)
  if(CMAKE_OSX_ARCHITECTURES MATCHES "^(arm64|aarch64)$" OR
      (NOT CMAKE_OSX_ARCHITECTURES AND
       CMAKE_SYSTEM_PROCESSOR MATCHES "^(arm64|aarch64)$"))
    set(ARIA2_OPENSSL_TARGET darwin64-arm64-cc)
  else()
    set(ARIA2_OPENSSL_TARGET darwin64-x86_64-cc)
  endif()
elseif(ANDROID)
  set(ARIA2_OPENSSL_TARGET android-arm64)
elseif(WIN32)
  if(CMAKE_SYSTEM_PROCESSOR MATCHES "^(arm64|aarch64)$")
    set(ARIA2_OPENSSL_TARGET mingw-arm64)
  else()
    set(ARIA2_OPENSSL_TARGET mingw64)
  endif()
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(arm64|aarch64)$")
  set(ARIA2_OPENSSL_TARGET linux-aarch64)
else()
  set(ARIA2_OPENSSL_TARGET linux-x86_64)
endif()

set(ARIA2_OPENSSL_CONFIG_ARGS)
if(WIN32 AND CMAKE_SYSTEM_PROCESSOR MATCHES "^(arm64|aarch64)$")
  list(APPEND ARIA2_OPENSSL_CONFIG_ARGS
    --config=${CMAKE_SOURCE_DIR}/packaging/openssl/mingw-arm64.conf
    no-asm)
endif()

set(ARIA2_OPENSSL_ENV
  CPPFLAGS=
  CFLAGS=
  CXXFLAGS=
  LDFLAGS=)
if(CMAKE_C_COMPILER)
  set(ARIA2_OPENSSL_CC ${CMAKE_C_COMPILER})
  if(DEFINED ENV{CC} AND NOT "$ENV{CC}" STREQUAL "")
    set(ARIA2_OPENSSL_CC $ENV{CC})
  endif()
  list(APPEND ARIA2_OPENSSL_ENV CC=${ARIA2_OPENSSL_CC})
endif()
if(CMAKE_CXX_COMPILER)
  list(APPEND ARIA2_OPENSSL_ENV CXX=${CMAKE_CXX_COMPILER})
endif()
if(CMAKE_AR)
  list(APPEND ARIA2_OPENSSL_ENV AR=${CMAKE_AR})
endif()
if(CMAKE_RANLIB)
  list(APPEND ARIA2_OPENSSL_ENV RANLIB=${CMAKE_RANLIB})
endif()
if(CMAKE_RC_COMPILER)
  list(APPEND ARIA2_OPENSSL_ENV RC=${CMAKE_RC_COMPILER})
endif()
if(ANDROID)
  list(APPEND ARIA2_OPENSSL_CONFIG_ARGS
    -D__ANDROID_API__=${CMAKE_SYSTEM_VERSION})
  list(APPEND ARIA2_OPENSSL_ENV
    ANDROID_NDK_HOME=${CMAKE_ANDROID_NDK}
    ANDROID_NDK_ROOT=${CMAKE_ANDROID_NDK})
endif()
if(APPLE)
  list(APPEND ARIA2_OPENSSL_ENV
    MACOSX_DEPLOYMENT_TARGET=${CMAKE_OSX_DEPLOYMENT_TARGET})
endif()

if(CMAKE_C_FLAGS)
  separate_arguments(ARIA2_OPENSSL_C_FLAGS NATIVE_COMMAND "${CMAKE_C_FLAGS}")
  list(FILTER ARIA2_OPENSSL_C_FLAGS EXCLUDE REGEX
    "^-f(file|debug)-prefix-map=")
  list(APPEND ARIA2_OPENSSL_CONFIG_ARGS ${ARIA2_OPENSSL_C_FLAGS})
endif()

ExternalProject_Add(openssl_project
  EXCLUDE_FROM_ALL TRUE
  SOURCE_DIR "${ARIA2_VENDOR_ROOT}/openssl"
  BINARY_DIR "${CMAKE_BINARY_DIR}/vendor/openssl"
  CONFIGURE_COMMAND
    ${CMAKE_COMMAND} -E env ${ARIA2_OPENSSL_ENV}
    ${PERL_EXECUTABLE} <SOURCE_DIR>/Configure
      ${ARIA2_OPENSSL_TARGET}
      ${ARIA2_OPENSSL_CONFIG_ARGS}
      no-shared
      no-module
      no-tests
      no-apps
      no-autoload-config
      --prefix=/
      --openssldir=/etc/ssl
      --libdir=lib
  BUILD_COMMAND
    ${ARIA2_MAKE_EXECUTABLE} -j${ARIA2_BUILD_JOBS}
  INSTALL_COMMAND
    ${ARIA2_MAKE_EXECUTABLE}
      DESTDIR=${ARIA2_DEPENDENCY_PREFIX} install_sw
  UPDATE_COMMAND ""
  TEST_COMMAND "")

set(ARIA2_LIBSSH2_DEPENDENCIES)
set(ARIA2_LIBSSH2_CRYPTO_BACKEND OpenSSL)
set(ARIA2_LIBSSH2_CRYPTO_ARGS
  -DOPENSSL_ROOT_DIR=${ARIA2_DEPENDENCY_PREFIX}
  -DOPENSSL_USE_STATIC_LIBS=ON
  -DOPENSSL_INCLUDE_DIR=${ARIA2_DEPENDENCY_PREFIX}/include
  -DOPENSSL_CRYPTO_LIBRARY=${ARIA2_DEPENDENCY_PREFIX}/lib/libcrypto.a
  -DOPENSSL_SSL_LIBRARY=${ARIA2_DEPENDENCY_PREFIX}/lib/libssl.a)
if(WIN32)
  set(ARIA2_LIBSSH2_CRYPTO_BACKEND WinCNG)
  set(ARIA2_LIBSSH2_CRYPTO_ARGS)
else()
  list(APPEND ARIA2_LIBSSH2_DEPENDENCIES openssl_project)
endif()

ExternalProject_Add(libssh2_project
  DEPENDS ${ARIA2_LIBSSH2_DEPENDENCIES}
  SOURCE_DIR "${ARIA2_VENDOR_ROOT}/libssh2"
  BINARY_DIR "${CMAKE_BINARY_DIR}/vendor/libssh2"
  CMAKE_ARGS
    ${ARIA2_EXTERNAL_CMAKE_ARGS}
    -DBUILD_SHARED_LIBS=OFF
    -DBUILD_EXAMPLES=OFF
    -DBUILD_TESTING=OFF
    -DCRYPTO_BACKEND=${ARIA2_LIBSSH2_CRYPTO_BACKEND}
    -DENABLE_ZLIB_COMPRESSION=OFF
    ${ARIA2_LIBSSH2_CRYPTO_ARGS}
  UPDATE_COMMAND ""
  TEST_COMMAND "")

ExternalProject_Add(nghttp2_project
  SOURCE_DIR "${ARIA2_VENDOR_ROOT}/nghttp2"
  BINARY_DIR "${CMAKE_BINARY_DIR}/vendor/nghttp2"
  CMAKE_ARGS
    ${ARIA2_EXTERNAL_CMAKE_ARGS}
    -DENABLE_LIB_ONLY=ON
    -DBUILD_SHARED_LIBS=OFF
    -DBUILD_STATIC_LIBS=ON
    -DBUILD_TESTING=OFF
    -DCMAKE_DISABLE_FIND_PACKAGE_OpenSSL=TRUE
    -DCMAKE_DISABLE_FIND_PACKAGE_Libngtcp2=TRUE
    -DCMAKE_DISABLE_FIND_PACKAGE_Libnghttp3=TRUE
    -DCMAKE_DISABLE_FIND_PACKAGE_Systemd=TRUE
    -DCMAKE_DISABLE_FIND_PACKAGE_Jansson=TRUE
    -DCMAKE_DISABLE_FIND_PACKAGE_Libevent=TRUE
    -DCMAKE_DISABLE_FIND_PACKAGE_LibXml2=TRUE
    -DCMAKE_DISABLE_FIND_PACKAGE_Jemalloc=TRUE
  UPDATE_COMMAND ""
  TEST_COMMAND "")

set(ARIA2_CURL_DEPENDENCIES
  zlib_project
  libssh2_project
  nghttp2_project)
set(ARIA2_CURL_TLS_ARGS
  -DCURL_USE_OPENSSL=ON
  -DOPENSSL_ROOT_DIR=${ARIA2_DEPENDENCY_PREFIX}
  -DOPENSSL_USE_STATIC_LIBS=ON
  -DOPENSSL_INCLUDE_DIR=${ARIA2_DEPENDENCY_PREFIX}/include
  -DOPENSSL_CRYPTO_LIBRARY=${ARIA2_DEPENDENCY_PREFIX}/lib/libcrypto.a
  -DOPENSSL_SSL_LIBRARY=${ARIA2_DEPENDENCY_PREFIX}/lib/libssl.a)
list(APPEND ARIA2_CURL_DEPENDENCIES openssl_project)
if(WIN32)
  set(ARIA2_CURL_TLS_ARGS
    -DCURL_USE_OPENSSL=OFF
    -DCURL_USE_SCHANNEL=ON)
  set(ARIA2_CURL_TRUST_DEFINE USE_SCHANNEL)
  list(REMOVE_ITEM ARIA2_CURL_DEPENDENCIES openssl_project)
elseif(APPLE)
  list(APPEND ARIA2_CURL_TLS_ARGS
    -DUSE_APPLE_SECTRUST=ON
    -DCURL_CA_BUNDLE=none
    -DCURL_CA_PATH=none)
  set(ARIA2_CURL_TRUST_DEFINE USE_APPLE_SECTRUST)
else()
  list(APPEND ARIA2_CURL_TLS_ARGS
    -DCURL_CA_BUNDLE=none
    -DCURL_CA_PATH=none
    -DCURL_CA_FALLBACK=ON)
  set(ARIA2_CURL_TRUST_DEFINE CURL_CA_FALLBACK)
endif()

ExternalProject_Add(curl_project
  DEPENDS ${ARIA2_CURL_DEPENDENCIES}
  SOURCE_DIR "${ARIA2_VENDOR_ROOT}/curl"
  BINARY_DIR "${CMAKE_BINARY_DIR}/vendor/curl"
  CMAKE_ARGS
    ${ARIA2_EXTERNAL_CMAKE_ARGS}
    -DBUILD_CURL_EXE=OFF
    -DBUILD_EXAMPLES=OFF
    -DBUILD_SHARED_LIBS=OFF
    -DBUILD_STATIC_LIBS=ON
    -DBUILD_TESTING=OFF
    -DCMAKE_DISABLE_FIND_PACKAGE_Perl=TRUE
    -DCURL_DISABLE_INSTALL=OFF
    -DCURL_USE_PKGCONFIG=OFF
    -DCURL_USE_CMAKECONFIG=OFF
    -DENABLE_ARES=OFF
    -DENABLE_THREADED_RESOLVER=ON
    -DCURL_USE_LIBSSH2=ON
    -DLIBSSH2_USE_STATIC_LIBS=ON
    -DLIBSSH2_INCLUDE_DIR=${ARIA2_DEPENDENCY_PREFIX}/include
    -DLIBSSH2_LIBRARY=${ARIA2_DEPENDENCY_PREFIX}/lib/libssh2.a
    -DUSE_NGHTTP2=ON
    -DNGHTTP2_USE_STATIC_LIBS=ON
    -DNGHTTP2_INCLUDE_DIR=${ARIA2_DEPENDENCY_PREFIX}/include
    -DNGHTTP2_LIBRARY=${ARIA2_DEPENDENCY_PREFIX}/lib/libnghttp2.a
    -DCURL_ZLIB=ON
    -DZLIB_ROOT=${ARIA2_DEPENDENCY_PREFIX}
    -DZLIB_USE_STATIC_LIBS=ON
    -DZLIB_INCLUDE_DIR=${ARIA2_DEPENDENCY_PREFIX}/include
    -DZLIB_LIBRARY=${ARIA2_DEPENDENCY_PREFIX}/lib/libz.a
    -DCURL_BROTLI=OFF
    -DCURL_ZSTD=OFF
    -DUSE_LIBIDN2=OFF
    -DCURL_DISABLE_ALTSVC=ON
    -DCURL_DISABLE_AWS=ON
    -DCURL_DISABLE_DICT=ON
    -DCURL_DISABLE_DOH=ON
    -DCURL_DISABLE_FILE=ON
    -DCURL_DISABLE_FTP=ON
    -DCURL_DISABLE_GOPHER=ON
    -DCURL_DISABLE_HSTS=ON
    -DCURL_DISABLE_IMAP=ON
    -DCURL_DISABLE_IPFS=ON
    -DCURL_DISABLE_LDAP=ON
    -DCURL_DISABLE_LDAPS=ON
    -DCURL_DISABLE_MQTT=ON
    -DCURL_DISABLE_NETRC=OFF
    -DCURL_DISABLE_POP3=ON
    -DCURL_DISABLE_RTSP=ON
    -DCURL_DISABLE_SMTP=ON
    -DCURL_DISABLE_TELNET=ON
    -DCURL_DISABLE_TFTP=ON
    -DCURL_DISABLE_WEBSOCKETS=ON
    -DCURL_USE_LIBPSL=OFF
    -DCURL_USE_GSSAPI=OFF
    ${ARIA2_CURL_TLS_ARGS}
  UPDATE_COMMAND ""
  TEST_COMMAND "")

ExternalProject_Add_Step(curl_project verify-trust-policy
  COMMAND ${CMAKE_COMMAND}
    -DHEADER=<BINARY_DIR>/lib/curl_config.h
    -DEXPECTED_DEFINE=${ARIA2_CURL_TRUST_DEFINE}
    -P ${CMAKE_SOURCE_DIR}/cmake/scripts/VerifyCurlTrust.cmake
  DEPENDEES configure
  DEPENDERS build)

if(ARIA2_ENABLE_BITTORRENT)
  ExternalProject_Add(libtorrent_project
    DEPENDS openssl_project
    SOURCE_DIR "${ARIA2_VENDOR_ROOT}/libtorrent"
    BINARY_DIR "${CMAKE_BINARY_DIR}/vendor/libtorrent"
    CMAKE_ARGS
      ${ARIA2_EXTERNAL_CMAKE_ARGS}
      -DBUILD_SHARED_LIBS=OFF
      -DBoost_INCLUDE_DIR=${ARIA2_VENDOR_ROOT}/boost
      -DBoost_NO_BOOST_CMAKE=ON
      -DOPENSSL_ROOT_DIR=${ARIA2_DEPENDENCY_PREFIX}
      -DOPENSSL_USE_STATIC_LIBS=ON
      -DOPENSSL_INCLUDE_DIR=${ARIA2_DEPENDENCY_PREFIX}/include
      -DOPENSSL_CRYPTO_LIBRARY=${ARIA2_DEPENDENCY_PREFIX}/lib/libcrypto.a
      -DOPENSSL_SSL_LIBRARY=${ARIA2_DEPENDENCY_PREFIX}/lib/libssl.a
      -Dbuild_tests=OFF
      -Dbuild_examples=OFF
      -Dbuild_tools=OFF
      -Dpython-bindings=OFF
      -Ddeprecated-functions=OFF
      -Dextensions=ON
      -Dmutable-torrents=ON
      -Dstreaming=ON
      -Di2p=OFF
      -Dwebtorrent=OFF
      -Dlogging=ON
      -Dencryption=ON
      -Ddht=ON
    UPDATE_COMMAND ""
    TEST_COMMAND "")
endif()

include(${CMAKE_CURRENT_LIST_DIR}/Media.cmake)

set(ARIA2_INNER_CMAKE_ARGS
  ${ARIA2_EXTERNAL_CMAKE_ARGS}
  -DARIA2_SUPERBUILD=OFF
  -DCMAKE_PREFIX_PATH=${ARIA2_DEPENDENCY_PREFIX}
  -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=${CMAKE_BINARY_DIR}
  -DARIA2_DEPENDENCY_ROOT=${ARIA2_DEPENDENCY_PREFIX}
  -DARIA2_BOOST_ROOT=${ARIA2_VENDOR_ROOT}/boost
  -DBoost_INCLUDE_DIR=${ARIA2_VENDOR_ROOT}/boost
  -DBoost_NO_BOOST_CMAKE=ON
  -DBOOST_ROOT=${ARIA2_VENDOR_ROOT}/boost
  -DOPENSSL_ROOT_DIR=${ARIA2_DEPENDENCY_PREFIX}
  -DOPENSSL_USE_STATIC_LIBS=ON)

foreach(variable
    BUILD_TESTING
    CMAKE_EXPORT_COMPILE_COMMANDS
    ARIA2_ENABLE_BITTORRENT
    ARIA2_ENABLE_METALINK
    ARIA2_ENABLE_WEBSOCKET
    ARIA2_ENABLE_EPOLL
    ARIA2_ENABLE_LIBARIA2
    ARIA2_ENABLE_WERROR
    ARIA2_RELEASE_SIZE_OPTIMIZED
    ARIA2_RELEASE_LTO)
  if(DEFINED ${variable})
    list(APPEND ARIA2_INNER_CMAKE_ARGS -D${variable}=${${variable}})
  endif()
endforeach()

set(ARIA2_PROJECT_DEPENDENCIES
  zlib_project
  expat_project
  sqlite_project
  openssl_project
  libssh2_project
  nghttp2_project
  curl_project
  ffmpeg_project
  gpac_project)
if(ARIA2_ENABLE_BITTORRENT)
  list(APPEND ARIA2_PROJECT_DEPENDENCIES libtorrent_project)
endif()

add_custom_target(aria2_dependencies DEPENDS ${ARIA2_PROJECT_DEPENDENCIES})

ExternalProject_Add(aria2_project
  DEPENDS ${ARIA2_PROJECT_DEPENDENCIES}
  SOURCE_DIR "${CMAKE_SOURCE_DIR}"
  BINARY_DIR "${ARIA2_INNER_BINARY_DIR}"
  CMAKE_ARGS ${ARIA2_INNER_CMAKE_ARGS}
  BUILD_ALWAYS ON
  INSTALL_COMMAND ""
  UPDATE_COMMAND ""
  TEST_COMMAND "")

enable_testing()
add_test(NAME aria2-tests
  COMMAND ${CMAKE_CTEST_COMMAND}
    --test-dir "${ARIA2_INNER_BINARY_DIR}"
    --output-on-failure)
